# version: '3.3'
# services:
#   database:
#     image: mysql:5.6
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'foodprint'
#       MYSQL_USER: 'admin'
#       MYSQL_PASSWORD: 'qwertyui123'
#       MYSQL_ROOT_PASSWORD: 'qwertyui123'
#     ports:
#       - '3306:3306'
#     expose:
#       - '3306'
#     volumes:
#       - foodprint-db:/var/lib/database
# volumes:
#   foodprint-db:
version: '3.3'
services:
  database:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'foodprint'
      MYSQL_USER: 'rootnew'
      MYSQL_PASSWORD: 'aalok21004'
      MYSQL_ROOT_PASSWORD: 'aalok7272'
    ports:
      - '3308:3308'
    expose:
      - '3308'
    volumes:
      - foodprint-db:/var/lib/database
volumes:
  foodprint-db: